### PR TITLE
error notification

### LINKED ISSUE #351: Improve web page to support display error msg if query failed.
**你的功能请求是否与问题有关？请描述。**
清晰简洁地描述问题是什么

**描述你想要的解决方案**。
简明扼要地描述你希望发生什么。

**描述你考虑过的替代方案**。
简明扼要地描述你考虑过的任何替代解决方案或功能。

**额外的背景**
在此添加关于该功能请求的任何其他背景或屏幕截图。

### PR DESCRIPTION
**Pull request by jxnu-liguobin**

### CODE REVIEW

File: bitlap-network/src/main/scala/org/bitlap/network/DriverAsyncRpc.scala [hunk 1]
```diff
@@ -29,15 +28,12 @@ trait DriverAsyncRpc extends DriverRpc[Task] { self =>
 
   def sync[T, E <: Throwable, Z <: ZIO[_, _, _]](
     action: self.type => Z
-  )(implicit runtime: zio.Runtime[Any] = runtime): T =
+  ): T =
     try {
-      val cancelableFuture = runtime.unsafeRunToFuture(action(this).asInstanceOf[ZIO[Any, E, T]])
-      Await.result(cancelableFuture.future, timeout)
+      val future = this.runtime.unsafeRunToFuture(action(this).asInstanceOf[ZIO[Any, E, T]])
+      Await.result(future, timeout)
```
Comment (jxnu-liguobin) [inline bitlap-network/src/main/scala/org/bitlap/network/DriverAsyncRpc.scala:34]: 不能直接unsaferun h会被zio包装为fiber trace
